Add -fgnu89-inline to CFLAGS
In GCC 5.1 default C standard changed to -std=gnu11. This changed behavior of
inline functions. Build error is:
[   83s] asn.1/ldap_key_seq.so: In function `asn1buf_insert_octet':
[   83s] /home/abuild/rpmbuild/BUILD/krb5-1.10.2/src/lib/krb5/asn.1/asn1buf.h:152: multiple definition of `asn1buf_insert_octet'
[   83s] asn.1/asn1_decode.so:/home/abuild/rpmbuild/BUILD/krb5-1.10.2/src/lib/krb5/asn.1/asn1buf.h:152: first defined here
[   83s] collect2: error: ld returned 1 exit status

Changing back to gnu89 inlining mode fixes the issue.

Change-Id: I6e3e1c874e2a56b643cbd396570877275fb2d6fa
Signed-off-by: Yury Usishchev <y.usishchev@samsung.com>